[profile.default]
src = "scripts"
out = "out"
libs = ["lib"]
solc_version = "0.8.23"
optimizer = true
optimizer_runs = 200
via_ir = false

[rpc_endpoints]
base = "${BASE_RPC_URL}"

[etherscan]
base = { key = "${BASESCAN_API_KEY}" }
